version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./wsgi.py:/app/wsgi.py
      - ./requirements.txt:/app/requirements.txt
    depends_on:
      - db
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=1
      - DATABASE_URL=mysql+pymysql://user:password@db/user_management
      - SECRET_KEY=your_secret_key_here
    working_dir: /app

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=user_management
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 